"""
parser/workspace.py
===================
Shared devspace dependency manifest.

A devspace is a directory containing multiple S-IDE projects. Instead of
each project managing its own virtual environment and installing the same
packages repeatedly, the devspace maintains a single package manifest.

At development time: packages are resolved once at the devspace level.
Projects reference them by name. The parser emits `isExternal` edges for
third-party imports — these are the hooks for the resolver.

At build time: the packager copies only the packages a project actually
imports into the output bundle.

Manifest file: <devspace_root>/.side-workspace.json

Format:
    {
      "name": "my-devspace",
      "python": "3.11",
      "packages": {
        "requests":  ">=2.28",
        "numpy":     ">=1.24",
        "rich":      "*"
      },
      "projects": [
        "myapp",
        "mylib",
        "tools/cli"
      ]
    }

Usage
-----
    from parser.workspace import (
        find_workspace_root, load_workspace, save_workspace,
        add_package, resolve_project_deps, WorkspaceManifest,
    )

    # Auto-detect workspace root from a project path
    ws_root = find_workspace_root("/home/user/DevOps/myproject")
    # → "/home/user/DevOps"

    manifest = load_workspace(ws_root)
    manifest.packages["requests"] = ">=2.28"
    save_workspace(ws_root, manifest)

    # Find which packages a project actually needs
    needed = resolve_project_deps("/home/user/DevOps/myproject", manifest)
    # → {"requests": ">=2.28"}
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Optional


WORKSPACE_FILE = ".side-workspace.json"


# ── Data types ────────────────────────────────────────────────────────────────

@dataclass
class WorkspaceManifest:
    """
    The devspace-level dependency manifest.

    All projects in the workspace can use any package listed here.
    The packager copies only the packages a project actually imports.
    """
    name:     str = "workspace"
    python:   str = "3.11"
    packages: dict[str, str] = field(default_factory=dict)  # name → version spec
    projects: list[str]      = field(default_factory=list)   # relative paths

    def to_dict(self) -> dict:
        return {
            "name":     self.name,
            "python":   self.python,
            "packages": self.packages,
            "projects": self.projects,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "WorkspaceManifest":
        return cls(
            name     = d.get("name", "workspace"),
            python   = d.get("python", "3.11"),
            packages = d.get("packages", {}),
            projects = d.get("projects", []),
        )

    def requirements_txt(self) -> str:
        """Generate a requirements.txt string for this manifest."""
        lines = [f"# Generated by S-IDE workspace manifest\n"]
        for pkg, spec in sorted(self.packages.items()):
            if spec and spec not in ("*", "any", ""):
                lines.append(f"{pkg}{spec}\n")
            else:
                lines.append(f"{pkg}\n")
        return "".join(lines)

    def add_package(self, name: str, spec: str = "*") -> None:
        """Add or update a package in the manifest."""
        self.packages[name] = spec

    def remove_package(self, name: str) -> bool:
        """Remove a package. Returns True if it was present."""
        if name in self.packages:
            del self.packages[name]
            return True
        return False


# ── Discovery ─────────────────────────────────────────────────────────────────

def find_workspace_root(project_path: str, max_depth: int = 4) -> Optional[str]:
    """
    Walk up from project_path to find a directory with .side-workspace.json.

    Args:
        project_path: Path to a project or any path within it.
        max_depth:    How many levels to walk up (default 4).

    Returns:
        Absolute path to the workspace root, or None if not found.
    """
    path = os.path.abspath(project_path)
    if not os.path.isdir(path):
        path = os.path.dirname(path)

    for _ in range(max_depth):
        if os.path.isfile(os.path.join(path, WORKSPACE_FILE)):
            return path
        parent = os.path.dirname(path)
        if parent == path:  # filesystem root
            break
        path = parent
    return None


def find_projects_in_workspace(workspace_root: str) -> list[str]:
    """
    Scan a workspace root directory for S-IDE projects.

    A project is a directory containing side.project.json.

    Returns:
        List of relative paths to project directories.
    """
    projects = []
    for item in os.listdir(workspace_root):
        if item.startswith("."):
            continue
        candidate = os.path.join(workspace_root, item)
        if os.path.isdir(candidate):
            if os.path.isfile(os.path.join(candidate, "side.project.json")):
                projects.append(item)
    return sorted(projects)


# ── Load / save ────────────────────────────────────────────────────────────────

def load_workspace(workspace_root: str) -> WorkspaceManifest:
    """
    Load the workspace manifest from workspace_root/.side-workspace.json.
    Returns an empty manifest if the file doesn't exist yet.
    """
    path = os.path.join(workspace_root, WORKSPACE_FILE)
    if not os.path.isfile(path):
        return WorkspaceManifest(
            name     = os.path.basename(workspace_root),
            projects = find_projects_in_workspace(workspace_root),
        )
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return WorkspaceManifest.from_dict(data)
    except (json.JSONDecodeError, OSError):
        return WorkspaceManifest()


def save_workspace(workspace_root: str, manifest: WorkspaceManifest) -> str:
    """
    Write the manifest to workspace_root/.side-workspace.json.

    Returns:
        Absolute path to the written file.
    """
    path = os.path.join(workspace_root, WORKSPACE_FILE)
    tmp  = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(manifest.to_dict(), f, indent=2)
    os.replace(tmp, path)
    return path


def init_workspace(workspace_root: str, name: str = "") -> WorkspaceManifest:
    """
    Initialise a new workspace manifest in workspace_root.
    Scans for existing projects automatically.

    Returns:
        The created WorkspaceManifest.
    """
    manifest = WorkspaceManifest(
        name     = name or os.path.basename(workspace_root),
        projects = find_projects_in_workspace(workspace_root),
    )
    save_workspace(workspace_root, manifest)
    return manifest


# ── Dependency resolution ──────────────────────────────────────────────────────

def resolve_project_deps(
    project_root: str,
    manifest:     WorkspaceManifest,
    graph:        Optional[dict] = None,
) -> dict[str, str]:
    """
    Find which workspace packages a specific project actually imports.

    Uses the project graph's `isExternal` edges if available (fast),
    otherwise scans source files for import statements (slower).

    Args:
        project_root: Absolute path to the project.
        manifest:     The workspace manifest to resolve against.
        graph:        Optional parsed project graph dict for faster lookup.

    Returns:
        Dict of {package_name: version_spec} for packages this project uses.
    """
    if not manifest.packages:
        return {}

    imported_names = _collect_external_imports(project_root, graph)
    needed: dict[str, str] = {}

    for pkg, spec in manifest.packages.items():
        # Check exact name match or top-level package match
        # e.g. "requests" matches "import requests" or "from requests import get"
        pkg_lower = pkg.lower().replace("-", "_")
        for imp in imported_names:
            imp_top = imp.split(".")[0].lower().replace("-", "_")
            if imp_top == pkg_lower:
                needed[pkg] = spec
                break

    return needed


def _collect_external_imports(
    project_root: str,
    graph:        Optional[dict],
) -> set[str]:
    """
    Collect all external (non-project) import names from the project.

    Uses the graph's isExternal edges if available, otherwise scans .py files.
    """
    imports: set[str] = set()

    if graph:
        # Fast path: use pre-parsed graph data
        for node in graph.get("nodes", []):
            if node.get("isExternal"):
                # External nodes have IDs like "ext:requests"
                nid = node.get("id", "")
                if nid.startswith("ext:"):
                    imports.add(nid[4:])
        for edge in graph.get("edges", []):
            if edge.get("type") == "external":
                imports.add(edge.get("target", "").replace("ext:", ""))
        if imports:
            return imports

    # Slow path: scan .py files for import statements
    import re
    import_re = re.compile(
        r'^(?:import\s+([\w.]+)|from\s+([\w.]+)\s+import)', re.M)
    for dirpath, dirs, files in os.walk(project_root):
        dirs[:] = [d for d in dirs if d not in
                   ("__pycache__", ".git", ".venv", "venv", "dist")]
        for fname in files:
            if not fname.endswith(".py"):
                continue
            try:
                text = open(os.path.join(dirpath, fname),
                            encoding="utf-8", errors="ignore").read()
                for m in import_re.finditer(text):
                    name = (m.group(1) or m.group(2) or "").split(".")[0]
                    if name:
                        imports.add(name)
            except OSError:
                pass
    return imports


# ── Helpers ────────────────────────────────────────────────────────────────────

def add_package(
    workspace_root: str,
    name:           str,
    spec:           str = "*",
) -> WorkspaceManifest:
    """
    Add a package to the workspace manifest and save.

    Args:
        workspace_root: Workspace root directory.
        name:           Package name (e.g. "requests").
        spec:           Version specifier (e.g. ">=2.28" or "*").

    Returns:
        The updated manifest.
    """
    manifest = load_workspace(workspace_root)
    manifest.add_package(name, spec)
    save_workspace(workspace_root, manifest)
    return manifest


def workspace_summary(workspace_root: str) -> str:
    """Return a human-readable summary of the workspace manifest."""
    manifest = load_workspace(workspace_root)
    lines = [
        f"Workspace: {manifest.name}",
        f"Python:    {manifest.python}",
        f"Packages:  {len(manifest.packages)}",
        f"Projects:  {len(manifest.projects)}",
    ]
    if manifest.projects:
        for p in manifest.projects:
            lines.append(f"  - {p}")
    if manifest.packages:
        lines.append("Packages:")
        for pkg, spec in sorted(manifest.packages.items()):
            lines.append(f"  {pkg} {spec}")
    return "\n".join(lines)
